### PR TITLE
Update README.md

### LINKED ISSUE #39: Add Carthage compatibility badge to the README
Using [these instructions](https://github.com/Carthage/Carthage/blob/7a0153cc164e301c46527f6e20c886728a0dc218/README.md#declare-your-compatibility).

### PR DESCRIPTION
**Pull request by esttorhe**
Added `Carthage support` banner.
Fix #39 

I think putting it on top works best.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
IIRC it should be possible to have this to the right of the main heading, on the same line. Can you please try that?

**Comment by esttorhe** [comment]
@jspahrsummers this was the best I could come up with:
screen shot 2015-03-12 at 11 58 56

Basically ditched `markdown` in order to support having the header and the banner on the same line.
Hope its :ok: if not then feel free to just ditch the whole PR.

**Comment by jspahrsummers** [comment]
Sorry for the confusion—I just meant formatting it in the same way as the [ReactiveCocoa header](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/c28b67bfb0385bb3712ee2d34bb5642e104a32e9/README.md), with the badge immediately to the right of the name.

**Comment by esttorhe** [comment]
OK @jspahrsummers then it's next to the title with `Markdown` and linking to `Carthage`'s GitHub repo

**Comment by jspahrsummers** [comment]
Thanks! :sparkles:

**Pull request merged**
